### ISSUE TITLE
coverage of @media rule which has indent is broken in coverage report

### ISSUE THREAD

**Issue by pirosikick** [istanbuljs/puppeteer-to-istanbul#36]
Coverage of `@media` rule which has indent(tab or space) is broken in coverage report. 

```css
/* example.css */
/* @media without indent */
@media screen {
h1 {
  color: red;
}
}

/* @media with space indent */
@media screen {
  h1 {
    color: blue;
  }
}

/* @media with tab indent */
@media screen {
	h1 {
		color: yellow;
	}
}
```

A coverage report of the above css shows that a first line in `@media` which has indent isn't covered.

![image](https://user-images.githubusercontent.com/424903/63273861-b44abf00-c2d9-11e9-8116-a2143038c128.png)

The full example is pushed to the following repository:
https://github.com/pirosikick/puppeteer-coverage-bug-in-media-query
